#[path ="./test/_eigen/test.rs"]
mod _eigen;
#[path ="./test/_solve/test.rs"]
mod _solve;
#[path ="./test/_matrix/test.rs"]
mod _matrix;
#[path ="./test/_regression/test.rs"]
mod _regression;
#[path ="./test/_polynomial/test.rs"]
mod _polynomial;
